name: Build Push Image
on: [push, workflow_dispatch]
env:
  DOCKERHUB_USERNAME: enclarify
  DEBIAN_VERSION: 11.8-slim
jobs:
  build-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build debian-dind-rootless image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}
          context: .
          file: Dockerfile
          push: false
          load: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/debian-dind-rootless:${{ env.DEBIAN_VERSION }}-${{ github.ref_name }}
      - name: Publish debian-dind-rootless
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/debian-dind-rootless:${{ env.DEBIAN_VERSION }}-${{ github.ref_name }}
